id: A1A1F1981
title: Invoking the Blessings of the Kagyü Lineage—‘Dorjechang Thungma’
type: translation
pechas:
- ID8069ADB
- IB6D33EAE
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:29:57.231878
  last_modified_at: 2023-01-04 11:29:57.231891
  collections:
  - Bengar Jampal Zangpo
  - Works of Tibetan Masters
alignment_to_base:
  ID8069ADB/9E49: 88F2
  IB6D33EAE/9891: 88F2
